spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/certif
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      