spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/certif
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    generate-ddl: true
      